# Linear Regression

## Questions:

### What is the wikipedia link to the algorithm?

- https://en.wikipedia.org/wiki/Linear_regression

### Which type of machine learning algorithm is this?

- Supervised learning

### What is the best video tutorial on this algorithm?

- [Video](https://www.youtube.com/watch?v=ZkjP5RJLQF4)

### What is the best picture which describes the algorithm?

- ![Linear Regression](Images/LinearRegression.jpeg)

### What is one case for which the algorithm is used for?

- Company has saved sales data. If she does a linear regression with monthly sales and sales data the company can be eventually able to predict future sales.

## Sample data on which the algorithm gets proofed on:

choosing a pytorch model and than reimplementing this with vanilla python. Use scikit learn because its easier to use. I am a little bit stuck on that - need to come back to this

$y= \theta_0 + \theta_1 \cdot x_1 + \theta_2 \cdot x_2 + \cdots + \theta_n \cdot x_n$

$y =$ Dependent variable

$\theta_0$ = y intercept

$\theta_n= $ Slope coefficient 

$x_n=$ Independent variables 

## From scratch implementation.

Steps for reproducing the algorithm:
1. **Hypothesis**
    - finding the best theta values a
    - what are the best start parameter for linear regression - just start with one (is also something which I can figure out later through testing)
    - input is y and X (multiple variables)
    - function does calculate 
    - hypothesis returns y and gets x and thetas as an input X is numpy array
2. **Cost function** 
    - defines the difference between the predicted y and and the actual y 
    - root mean squared error is used for that
3. **Gradient descent**
4. **Linear regression**

later compare result to https://www.geeksforgeeks.org/gradient-descent-in-linear-regression/ at botton?

This steps need to be inputted into a final linear rgeression method 

I was stuck with my implementation. How can I porceed futher with success. I really need to clarify each term. And it would be good to be already sure on how to implement the whole algorithm. Should I go with the hundred page machine learning book or should i create my own links for good sources?

in the last step i need to compress everything in one method. this eg linear regression model which return first y with given data  than differences between real and predicted. i am not sure. mathmatically my goal is it to get the fit values of theta values. Because than i can calculate with X input every y.

In [12]:
import numpy as np

### Hypothesis

$y= \theta_1 \cdot x_1 + \theta_2 \cdot x_2 + \cdots + \theta_n \cdot x_n$

In [13]:
#returns y this does mean that I either hava a cosntructr with which i change theta values globally or variables
#single input x 
def hypothesis(X, thetas):
    #how the data looks like:
    #X = [[1,2,3], [1,2,3], [1,2,3], [1,2,3], [1,2,3]]
    #thetas = [1,2,3]
    '''version if several inputs for x 
    y=[]
    for i in range(len(X)):
        y = thetas[0] + sum(thetas[1:] * X[i])
    return y'''    
    '''version if one input for x 
    y = thetas[0] + sum(thetas[1:] * X)
    return y'''
    #inspired by https://ml-cheatsheet.readthedocs.io/en/latest/linear_regression.html#multivariable-regression
    #can't multiply sequence by non-int of type 'list'
    print(thetas)
    print(X)
    y = np.dot(thetas, X)
    return y 

### Cost function

$J = \frac{1}{2n}\sum_{i=1}^{n}(y_i - (\theta_1 \cdot x_1 + \theta_2 \cdot x_2 + \cdots + \theta_n \cdot x_n))^2$

In [14]:
#calc error of all tuples (X,y) N 
#for that the function needs theta values, for hypothesis, X values for hypothesis and y values for comparing 
def costFunction(thetas, X, y):
    sumVal = 0
    for i in range(len(X)):
        sumVal = sumVal + (y[i] - hypothesis(X[i], thetas))**2
    j = 1/2*len(X) * sumVal
    return j
    

### Gradient descent

Using chain rule for creating partial derivative of each $\theta$.

$f'(\theta_1) = -x_1(y - (\theta_1 x_1 + \theta_2 x_2 + \cdots + \theta_n x_n)) \\$
$f'(\theta_2) = -x_2(y - (\theta_1 x_1 + \theta_2 x_2 + \cdots + \theta_n x_n)) \\$
$\vdots\\$
$f'(\theta_n) = -x_3(y - (\theta_1 x_1 + \theta_2 x_2 + \cdots + \theta_n x_n))$


In [20]:
def updateTheta(thetas,X, y, learningRate):
    #have thetas and need to adjust them so that they fit the best line. first i calc y with an weights all initiliazed with 1 and get prob an huge error. dann muss ich solange weights verändern bis der error sich nicht mehr verändert.
    #this does mean i need to calculate the old theta - the new theta. I dont need a learning raet for that thats just something for speeding things up.
    #iter over all thetas and get new theta value for every theta and store in list 
    thetasNew = []

    for i in thetas:
        print(thetas[i])
        print(learningRate)
        print(-X[i])
        print(y[i])
        print(np.dot(X[i],thetas))
        1
0.01
[-1 -2 -3 -5]
2
11

            
        #1 - 0.01 * ()
        thetaNew = thetas[i] - learningRate*(-X[i](y[i]-(np.dot(X[i],thetas))))
        thetasNew.append(thetaNew)
    return thetaNew

In [21]:
#now implementing all steps for creating a model to use
#need some sample data for the model
#with setted values build model

def linearRegression(X, y, thetas, iterations, learningRate):
    '''
    1. Get first y 
    2. 
    '''
    costFunctionResults = []
    thetasResults = []
    for i in range(iterations):
        for i in range(len(X)):
            j = costFunction(thetas, X, y)
            thetas = updateTheta(thetas, X, y, learningRate)
            costFunctionResults.append(j)
            thetasResults.append(thetas)
    return costFunctionResults, thetasResults
        

In [22]:
X = np.array([[1,2,3,4], [1,2,3,5], [1,2,4,4], [3,5,6,6], [5,7,8,9]])
y = np.array([1,2,3,4,5])
thetas = np.array([1,1,1,1])
iterations = 500
learningRate = 0.01
linearRegression(X, y, thetas, iterations, learningRate)

[1 1 1 1]
[1 2 3 4]
[1 1 1 1]
[1 2 3 5]
[1 1 1 1]
[1 2 4 4]
[1 1 1 1]
[3 5 6 6]
[1 1 1 1]
[5 7 8 9]
1
0.01
[-1 -2 -3 -5]
2
11


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
sexualActiviyWithWomans = 0 
sexualActiviyWithMens = 3 
bi = sexualActiviyWithMens/sexualActiviyWithMens
print(bi)

1.0


In [ ]:
'''
i ask myself how i can get the value from b. i mean thats the output value of the regression. I need a learning rate and backpropagation for that because otherwise. 
I need to start with some value. 

'''

#house prize = ? + floors
def linearRegression(y, X):
    for i in range(len(X)):
        
    

## Implementation with PyTorch